name: Gerar Animação

on:
  schedule:
    # Executa automaticamente a cada 24 horas
    - cron: "0 */24 * * *"
  push:
    # Executa em cada push na branch master/main
    branches:
      - main
      - master
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    permissions:
      contents: write # Permissão para escrever no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Yuriportf
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar github-contribution-grid-snake.svg para o branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
